FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# codebeerhorseman - ForasteiroBack

## Authentication Collection [/v1/api/authentication]
### checkToken [GET /v1/api/authentication/checkToken/{token}]

+ Parameters

    + token (string, required)

+ Response 200 (application/json)
        
        {
          "status": "success",
          "data": {
            "isValid" : true
          },
          "message": null /* Or optional success message */
        }
        
### login [POST /v1/api/authentication/login]
+ Request (application/json)

        {
            "email": "dandpb@gmail.com",
            "password": "123456"
        }

+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "token" : "qwerwdghfgbfg123",
            "username" : "Daniel",
            "expiredTime" : 12341234123
          },
          "message": null /* Or optional success message */
        }
### signUp [POST /v1/api/authentication/signUp]
+ Request (application/json)

        {
            "name": "Daniel Barreto",
            "birthDate": "17/07/1990",
            "rgRne": "477781127",
            "docIssuer": "SSP/SP",
            "cpf": "93002820261",
            "phone": "11984363878",
            "email": "dandpb@gmail.com",
            "password": "123456",
            "newletter": true,
            "facebookUser": "dandpb"
            
        }
        
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "token" : "qwerwdghfgbfg123",
            "name" : "Daniel",
            "expiredTime" : 12341234123
          },
          "message": null /* Or optional success message */
        }
### logout [POST /v1/api/authentication/logout]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {},
          "message": null /* Or optional success message */
        }

## User Collection [/v1/api/auth/user]
### get userData [GET /v1/api/auth/user/userData]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "name": "Daniel Barreto",
            "birthDate": "17/07/1990",
            "rgRne": "477781127",
            "docIssuer": "SSP/SP",
            "cpf": "93002820261",
            "phone": "11984363878",
            "email": "dandpb@gmail.com",
            "newletter": true,
            "facebookUser": "dandpb"
            },
          "message": null /* Or optional success message */
        }
### edit userData [PUT /v1/api/auth/user/userData]
+ Request (application/json)

        {
            "name": "Daniel Barreto",
            "birthDate": "17/07/1990",
            "rgRne": "477781127",
            "docIssuer": "SSP/SP",
            "cpf": "93002820261",
            "phone": "11984363878",
            "email": "dandpb@gmail.com",
            "newletter": true,
            "facebookUser": "dandpb"
            
        }
        
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "name" : "Daniel2"
          },
          "message": null /* Or optional success message */
        }
### change Password [PUT /v1/api/auth/user/changePassword]]
+ Request (application/json)

        {
            "oldPassword": "123456",
            "newPasswprd": "1234567"
            
        }
        
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
          },
          "message": null /* Or optional success message */
        }

## Event Collection [/event]
### nextEvents [GET /v1/api/event/nextEvents]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": [
          {
            "id" : "1",
            "title" : "Ilha do Cardoso",
            "data" : "17/01/2018",
           "price" : "R$ 1000,00,
          },
          {
            "id" : "2",
            "title" : "Tridade",
            "data" : "17/07/2018",
           "price" : "R$ 300,00,
          } 
          ],
          "message": null /* Or optional success message */
        }
### lastEvents [GET /v1/api/event/lastEvents]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": [
          {
            "id" : "1",
            "title" : "Ilha do Cardoso",
            "data" : "17/01/2018",
           "price" : "R$ 1000,00,
          },
          {
            "id" : "2",
            "title" : "Tridade",
            "data" : "17/07/2018",
           "price" : "R$ 300,00,
          } 
          ],
          "message": null /* Or optional success message */
        }
### searchEvent [POST /v1/api/event/searchEvent{?page,rpp,search,filter}]

## Parameters
    page (int) Número da pagina de pedido que será carregada
    rrp (int) resultados por página
    query (string) palavra procurada
    filter (string) filtro


+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
          "events":[
          {
            "id" : "1",
            "title" : "Ilha do Cardoso",
            "data" : "17/01/2018",
           "price" : "R$ 1000,00,
          },
          {
            "id" : "2",
            "title" : "Tridade",
            "data" : "17/07/2018",
           "price" : "R$ 300,00,
          } 
          ],
          "destinations":[
          {
            "id" : "1",
            "title" : "Ilha do Cardoso",
            "data" : "17/01/2018",
           "price" : "R$ 1000,00,
          },
          {
            "id" : "2",
            "title" : "Tridade",
            "data" : "17/07/2018",
           "price" : "R$ 300,00,
          } 
          ],
          "pagination": {
               "currentPage": 1,
               "totalPages": 1,
               "totalItems": 2
            }
          },
          "message": null /* Or optional success message */
        }
        
### eventDetail [GET /v1/api/event/eventDetail]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "isValid" : true
          },
          "message": null /* Or optional success message */
        }

## Destination Collection [/destination]
### possibleDestination [GET  /v1/api/destination/possibleDestination]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": [
          {
            "id" : "1",
            "title" : "Ilha do Cardoso",
            "data" : "17/01/2018",
           "price" : "R$ 1000,00,
          },
          {
            "id" : "2",
            "title" : "Tridade",
            "data" : "17/07/2018",
           "price" : "R$ 300,00,
          } 
          ],
          "message": null /* Or optional success message */
        }
        
### searchDestination [POST  /v1/api/destination/searchDestination]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
          "events":[
          {
            "id" : "1",
            "title" : "Ilha do Cardoso",
            "data" : "17/01/2018",
           "price" : "R$ 1000,00,
          },
          {
            "id" : "2",
            "title" : "Tridade",
            "data" : "17/07/2018",
           "price" : "R$ 300,00,
          } 
          ],
          "destinations":[
          {
            "id" : "1",
            "title" : "Ilha do Cardoso",
            "data" : "17/01/2018",
           "price" : "R$ 1000,00,
          },
          {
            "id" : "2",
            "title" : "Tridade",
            "data" : "17/07/2018",
           "price" : "R$ 300,00,
          } 
          ],
          "pagination": {
               "currentPage": 1,
               "totalPages": 1,
               "totalItems": 2
            }
          },
          "message": null /* Or optional success message */
        }
        
### destinationDetail [POST  /v1/api/destination/destinationDetail]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "isValid" : true
          },
          "message": null /* Or optional success message */
        }

## Purchase Collection [/purchase]
### orderDetail [GET /v1/api/auth/purchase/orderDetail]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "isValid" : true
          },
          "message": null /* Or optional success message */
        }
### finishOrder [POST /v1/api/auth/purchase/finishOrder]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "isValid" : true
          },
          "message": null /* Or optional success message */
        }
### myOrders [GET /v1/api/auth/purchase/myOrders]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "isValid" : true
          },
          "message": null /* Or optional success message */
        }
### depositReceipt [POST /v1/api/auth/purchase/depositReceipt]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "isValid" : true
          },
          "message": null /* Or optional success message */
        }
### giveup [POST /v1/api/auth/purchase/giveup]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "isValid" : true
          },
          "message": null /* Or optional success message */
        }
### sendObservation [GET /v1/api/auth/purchase/sendObservation]
+ Response 200 (application/json)

        {
          "status": "success",
          "data": {
            "isValid" : true
          },
          "message": null /* Or optional success message */
        }